### ISSUE TITLE
issue connecting the URLs

### ISSUE THREAD

**Issue by pabin-shrestha** [Anil-KHANAL/Tours-Management-system#6]
**Govind, I have encountered a similar issue as u had before but only giving the relevant URL path is not solving this.**

![issue](https://user-images.githubusercontent.com/81344509/118336872-4248ed80-b532-11eb-953b-94c481bf28d0.png)

**Comment by GovindBhusal007** [comment]
Pabin as you told me yesterday that you are working on different project before assembling the project with my bookingpage project so i believe you have not created a super user in your project because of which you are not allowed to access that command. So before accessing to admin page you must have to create a super user first and then the server will give you the access to admin panel.

**Comment by pabin-shrestha** [comment]
thank you, Govind.
I will try it and fix the error as you told me.

**Comment by pabin-shrestha** [comment]
### **Issue solved**
Govind as you told me to make the superuser first and the server will give access to the admin panel.
I did it and the issue is solved.
