### ISSUE TITLE
issue in running the server

### ISSUE THREAD

**Issue by pabin-shrestha** [Anil-KHANAL/Tours-Management-system#7]
### **As it was working previously but it is not working now. I have installed Django it stills gives the error to run the server. as it says it has not found 'manage.py 'directory.**

![issue2](https://user-images.githubusercontent.com/81344509/118350286-90331500-b575-11eb-8716-31074b8ea966.png)

**Comment by GovindBhusal007** [comment]
Pabin you are not inside the directory where you have created the project so there is no any file or folder named manage.py outside your created project that's why it is showing this problem. First of all, go inside the project you have created and run the command again as there is the file named 'manage.py' it will access your command perfectly.

**Comment by pabin-shrestha** [comment]
ohh i see Govind,
as I was out of the directory I was not able to run the server.
I have already solved the issue.

**Comment by Anil-KHANAL** [comment]
https://l.facebook.com/l.php?u=https%3A%2F%2Fcode.djangoproject.com%2Fticket%2F21875%3Ffbclid%3DIwAR04QfzPKHJ6H_JKyBAj3NmEP-mCMdodFZY0PYIpf67jr_EJ2U7hEiTNhkI&h=AT0wK-y_iRKor1ZqBOOkUIQcJu5inyKK-8UCC6JW4CneAkS1qXVqKMY7y4CJwQ51PE4Oh-U-Sp39xchY2HYtHLUQEFK8RSjkHVU5sMMpHcwvYSU0MGZGvEC8CJiOAxEIey9FbV9yKdHZTpw
